//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/InputSystem/CarInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @CarInputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CarInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CarInputSystem"",
    ""maps"": [
        {
            ""name"": ""Car"",
            ""id"": ""2e690355-79a2-42ca-ad12-a65302835c50"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""fa3f57f5-6e7f-4dc3-a521-c98ff744f0f3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SetStateEngine"",
                    ""type"": ""Button"",
                    ""id"": ""11938336-2938-43a0-890d-ac2870bfd310"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetStateLights"",
                    ""type"": ""Button"",
                    ""id"": ""3852326f-f56e-4619-8adc-e1c986d917ab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RefuelCar"",
                    ""type"": ""Button"",
                    ""id"": ""929e2db3-8a8b-4f34-9d27-03791ca4f1ce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpGear"",
                    ""type"": ""Button"",
                    ""id"": ""8ff20c92-f0cf-420b-9a43-9aa8f69e9d47"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownGear"",
                    ""type"": ""Button"",
                    ""id"": ""c35888f0-85f5-453a-a70e-fd1f8c7044da"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""24a0a749-f9fb-4272-8d78-56e63b7db49d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""99bedeef-6a8f-407d-9328-e81c10f253f1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e633ec4e-00ae-4bb3-a185-4dd890c909f0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""434dc2b7-fe4c-4281-94dd-23ace679fa29"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b69c7e48-3273-43cd-9e80-eccfb5cc23c8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow"",
                    ""id"": ""786bd983-2ba2-42a1-a4ba-fb422e130c43"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e4e8d09f-6cda-44ed-954c-e4205e56b3df"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""69044415-4424-42d9-b693-8ca1d83bdf56"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6d7527f6-9583-40dc-98ab-8dad207ab171"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9298df4a-f4df-40dc-b4fe-4dfeb8c0c22b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""141eefbe-7950-4b4b-9e9a-ff6b899c03d8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetStateEngine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aef6f841-e268-4e0c-91fe-39b0e4105472"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetStateLights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""265207a9-3e2f-4f01-ba2a-2b135a3dd54f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RefuelCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc1407de-04ff-4758-ab4c-fc1094ed2086"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpGear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f411a95-a493-4b91-b7e0-41a7bf43fe05"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownGear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Car
        m_Car = asset.FindActionMap("Car", throwIfNotFound: true);
        m_Car_Move = m_Car.FindAction("Move", throwIfNotFound: true);
        m_Car_SetStateEngine = m_Car.FindAction("SetStateEngine", throwIfNotFound: true);
        m_Car_SetStateLights = m_Car.FindAction("SetStateLights", throwIfNotFound: true);
        m_Car_RefuelCar = m_Car.FindAction("RefuelCar", throwIfNotFound: true);
        m_Car_UpGear = m_Car.FindAction("UpGear", throwIfNotFound: true);
        m_Car_DownGear = m_Car.FindAction("DownGear", throwIfNotFound: true);
    }

    ~@CarInputSystem()
    {
        Debug.Assert(!m_Car.enabled, "This will cause a leak and performance issues, CarInputSystem.Car.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Car
    private readonly InputActionMap m_Car;
    private List<ICarActions> m_CarActionsCallbackInterfaces = new List<ICarActions>();
    private readonly InputAction m_Car_Move;
    private readonly InputAction m_Car_SetStateEngine;
    private readonly InputAction m_Car_SetStateLights;
    private readonly InputAction m_Car_RefuelCar;
    private readonly InputAction m_Car_UpGear;
    private readonly InputAction m_Car_DownGear;
    public struct CarActions
    {
        private @CarInputSystem m_Wrapper;
        public CarActions(@CarInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Car_Move;
        public InputAction @SetStateEngine => m_Wrapper.m_Car_SetStateEngine;
        public InputAction @SetStateLights => m_Wrapper.m_Car_SetStateLights;
        public InputAction @RefuelCar => m_Wrapper.m_Car_RefuelCar;
        public InputAction @UpGear => m_Wrapper.m_Car_UpGear;
        public InputAction @DownGear => m_Wrapper.m_Car_DownGear;
        public InputActionMap Get() { return m_Wrapper.m_Car; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CarActions set) { return set.Get(); }
        public void AddCallbacks(ICarActions instance)
        {
            if (instance == null || m_Wrapper.m_CarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @SetStateEngine.started += instance.OnSetStateEngine;
            @SetStateEngine.performed += instance.OnSetStateEngine;
            @SetStateEngine.canceled += instance.OnSetStateEngine;
            @SetStateLights.started += instance.OnSetStateLights;
            @SetStateLights.performed += instance.OnSetStateLights;
            @SetStateLights.canceled += instance.OnSetStateLights;
            @RefuelCar.started += instance.OnRefuelCar;
            @RefuelCar.performed += instance.OnRefuelCar;
            @RefuelCar.canceled += instance.OnRefuelCar;
            @UpGear.started += instance.OnUpGear;
            @UpGear.performed += instance.OnUpGear;
            @UpGear.canceled += instance.OnUpGear;
            @DownGear.started += instance.OnDownGear;
            @DownGear.performed += instance.OnDownGear;
            @DownGear.canceled += instance.OnDownGear;
        }

        private void UnregisterCallbacks(ICarActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @SetStateEngine.started -= instance.OnSetStateEngine;
            @SetStateEngine.performed -= instance.OnSetStateEngine;
            @SetStateEngine.canceled -= instance.OnSetStateEngine;
            @SetStateLights.started -= instance.OnSetStateLights;
            @SetStateLights.performed -= instance.OnSetStateLights;
            @SetStateLights.canceled -= instance.OnSetStateLights;
            @RefuelCar.started -= instance.OnRefuelCar;
            @RefuelCar.performed -= instance.OnRefuelCar;
            @RefuelCar.canceled -= instance.OnRefuelCar;
            @UpGear.started -= instance.OnUpGear;
            @UpGear.performed -= instance.OnUpGear;
            @UpGear.canceled -= instance.OnUpGear;
            @DownGear.started -= instance.OnDownGear;
            @DownGear.performed -= instance.OnDownGear;
            @DownGear.canceled -= instance.OnDownGear;
        }

        public void RemoveCallbacks(ICarActions instance)
        {
            if (m_Wrapper.m_CarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICarActions instance)
        {
            foreach (var item in m_Wrapper.m_CarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CarActions @Car => new CarActions(this);
    public interface ICarActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSetStateEngine(InputAction.CallbackContext context);
        void OnSetStateLights(InputAction.CallbackContext context);
        void OnRefuelCar(InputAction.CallbackContext context);
        void OnUpGear(InputAction.CallbackContext context);
        void OnDownGear(InputAction.CallbackContext context);
    }
}
